parameters:
    onceit_raygun.exception_listener.class: Onceit\RaygunBundle\Listener\RaygunExceptionListener
    onceit_raygun.raygun.class:             Raygun4php\RaygunClient
    onceit_raygun.api_key:                  ~
    onceit_raygun.async_sending:            ~
    onceit_raygun.debug:                    ~

services:
    onceit_raygun.raygun:
        class:     "%onceit_raygun.raygun.class%"
        arguments: [onceit_raygun.api_key, onceit_raygun.async_sending, onceit_raygun.debug]
    onceit_raygun.exception_listener:
        class:     "%onceit_raygun.exception_listener.class%"
        arguments: ["@onceit_raygun.raygun"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            - { name: kernel.event_listener, event: console.exception, method: onConsoleException }
